set(CMAKE_SYSTEM_NAME Windows)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_SYSROOT_COMPILE "${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-w64-mingw32")

list(APPEND ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES} "/usr/x86_64-w64-mingw32/include")
list(APPEND ${CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES} "/usr/x86_64-w64-mingw32/include")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

